'use strict';
// Only the independent preview project is ever a synchronization target.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const {spawnSync} = require('node:child_process');
const ROOT = path.resolve(__dirname, '..');
const TARGET = Object.freeze({scriptId:'1W38Q5dAaGA2hRLO9ARI0_shwvxNanc8SBy1n77oVNunGHaQZ7kWG5pmv', spreadsheetId:'1TRYhl0WmqhEykYCvFtZzJG4J17YChKiqausAxT8iwHk', repository:'ponnhide/yachielab-preview', branch:'codex/preview'});
const hash = value => crypto.createHash('sha256').update(value).digest('hex');
const normalize = value => value.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n').replace(/\n+$/, '');
const secret = /(?:gh[pousr]_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]{20,}|-----BEGIN (?:RSA |EC )?PRIVATE KEY-----)/;

function assertGuard(source, target=TARGET) {
  for(const [name,value] of [['PREVIEW_SPREADSHEET_ID',target.spreadsheetId],['PREVIEW_REPOSITORY',target.repository],['PREVIEW_BRANCH',target.branch]]) {
    const match = source.match(new RegExp('(?:const|var)\\s+'+name+'\\s*=\\s*[\"\x27]([^\"\x27]+)[\"\x27]'));
    if(!match || match[1]!==value) throw Error('Preview target guard mismatch: '+name);
  }
}
function sourceBundle(root=ROOT, revision='uncommitted') {
  const directory=path.join(root,'cms'), files={};
  for(const name of fs.readdirSync(directory).sort()) {
    if(!/^(?:[A-Za-z_][A-Za-z0-9_]*\.gs|appsscript\.json)$/.test(name)) continue;
    if(name==='BuildInfo.gs') throw Error('BuildInfo.gs is generated in private staging, not a CMS source module.');
    const filename=path.join(directory,name);
    if(!fs.lstatSync(filename).isFile()) throw Error('CMS source must be a regular file: '+name);
    const source=fs.readFileSync(filename,'utf8');
    if(secret.test(source)) throw Error('Credential-like content in CMS source: '+name);
    files[name]=source;
  }
  for(const name of ['PreviewIsolation.gs','Cms.gs','RenderCache.gs','Renderer.gs','appsscript.json']) if(!files[name]) throw Error('Missing source module: '+name);
  assertGuard(files['PreviewIsolation.gs']);
  const manifest=JSON.parse(files['appsscript.json']);
  const scopes=['spreadsheets.currentonly','drive.readonly','script.external_request','script.container.ui'].map(x=>'https://www.googleapis.com/auth/'+x).sort();
  if(JSON.stringify((manifest.oauthScopes||[]).slice().sort())!==JSON.stringify(scopes)) throw Error('Unexpected runtime OAuth scopes.');
  if(manifest.runtimeVersion!=='V8') throw Error('Unexpected Apps Script runtime.');
  const sourceHashes=Object.fromEntries(Object.entries(files).map(([name,source])=>[name,hash(normalize(source))]));
  const fingerprint=hash(JSON.stringify(sourceHashes));
  // Read this at function-call time; Apps Script global file ordering is unspecified.
  files['BuildInfo.gs']='// Generated by scripts/gas_sync.cjs; no credentials.\nvar CMS_SOURCE_FINGERPRINT_ = '+JSON.stringify(fingerprint)+';\nvar CMS_SOURCE_GIT_REVISION_ = '+JSON.stringify(revision)+';\n';
  return {files,sourceHashes,fingerprint,revision};
}
function canonical(files) {
  return Object.fromEntries(Object.keys(files).sort().map(name=>[name,name==='appsscript.json'?JSON.stringify(JSON.parse(files[name])):normalize(files[name])]));
}
function differences(actual,expected) {
  const a=canonical(actual),e=canonical(expected);
  return [...new Set([...Object.keys(a),...Object.keys(e)])].sort().filter(name=>a[name]!==e[name]);
}
function writeProject(directory,files) {
  fs.mkdirSync(directory,{recursive:true,mode:0o700});
  for(const [name,source] of Object.entries(files)) fs.writeFileSync(path.join(directory,name),source,{mode:0o600});
  fs.writeFileSync(path.join(directory,'.clasp.json'),JSON.stringify({scriptId:TARGET.scriptId,parentId:TARGET.spreadsheetId,rootDir:'.',scriptExtensions:['gs'],skipSubdirectories:true},null,2),{mode:0o600});
  fs.writeFileSync(path.join(directory,'.claspignore'),'**/**\n!**/*.gs\n!**/appsscript.json\n');
}
function readProject(directory) {
  const files={};
  for(const name of fs.readdirSync(directory)) {
    if(!fs.lstatSync(path.join(directory,name)).isFile()) throw Error('Unexpected remote directory or symlink.');
    if(name==='appsscript.json') files[name]=fs.readFileSync(path.join(directory,name),'utf8');
    else if(/^[A-Za-z_][A-Za-z0-9_]*\.(?:gs|js)$/.test(name)) files[name.replace(/\.js$/,'.gs')]=fs.readFileSync(path.join(directory,name),'utf8');
    else if(/\.(?:gs|js|html|json)$/.test(name)&&!name.startsWith('.')) throw Error('Unexpected remote source file.');
  }
  assertGuard(files['PreviewIsolation.gs']||'');
  return files;
}
function validatePullRoster(result, allowed) {
  if(!result || !Array.isArray(result.pulledFiles) || !result.pulledFiles.length || !Array.isArray(result.deletedFiles) || result.deletedFiles.length) throw Error('Invalid remote pull roster.');
  const names=result.pulledFiles.map(name=>{
    if(typeof name!=='string' || !/^(?:[A-Za-z_][A-Za-z0-9_]*\.(?:gs|js)|appsscript\.json)$/.test(name)) throw Error('Unmanaged remote module; sync stopped.');
    const normalized=name.replace(/\.js$/,'.gs');
    if(!Object.prototype.hasOwnProperty.call(allowed,normalized)) throw Error('Unmanaged remote module; sync stopped.');
    return {local:name,normalized};
  });
  if(new Set(names.map(x=>x.normalized)).size!==names.length || !names.some(x=>x.normalized==='appsscript.json') || !names.some(x=>x.normalized==='PreviewIsolation.gs')) throw Error('Invalid remote pull roster.');
  return names;
}
function synchronize({bundle,before,stage,after,pull,push,validate=()=>{}}) {
  // Recheck tests and destination immediately before the one remote mutation.
  validate(); pull(before); const original=readProject(before);
  const allowed=new Set([...Object.keys(bundle.files),'BuildInfo.gs']);
  if(Object.keys(original).some(name=>!allowed.has(name))) throw Error('Unmanaged remote module; sync stopped.');
  if(differences(original,bundle.files).length===0) return {changed:false,verified:true};
  writeProject(stage,bundle.files); push(stage); pull(after);
  const mismatches=differences(readProject(after),bundle.files);
  if(mismatches.length) throw Error('Remote readback mismatch: '+mismatches.join(', ')+'; private before-snapshot retained.');
  return {changed:true,verified:true};
}
function run(command,args,options={}) {
  const env={...process.env}; delete env.DEBUG; delete env.clasp_config_auth; delete env.clasp_config_project; delete env.clasp_config_ignore;
  const result=spawnSync(command,args,{cwd:ROOT,encoding:'utf8',shell:false,env,...options});
  if(result.error||result.status!==0) {
    const output=String(result.stderr||'')+String(result.stdout||'');
    const reason=/not logged in|No credentials|not authorized|login/i.test(output)?'Google authorization required':/403|disabled|not been used|accessNotConfigured/i.test(output)?'Apps Script API or account permission unavailable':'command failed';
    throw Error(reason+' (output withheld).');
  }
  return String(result.stdout||'').trim();
}
function assertCheckout(clean=false) {
  if(run('git',['branch','--show-current'])!==TARGET.branch) throw Error('Only codex/preview is allowed.');
  const url=run('git',['remote','get-url','yachielab-preview']);
  if(!/^(?:https:\/\/github\.com\/|git@github\.com:)ponnhide\/yachielab-preview(?:\.git)?$/.test(url)) throw Error('Unexpected preview remote.');
  if(clean&&run('git',['status','--porcelain'])) throw Error('Commit reviewed source changes before synchronization.');
}
function main(mode) {
  if(!['plan','auth','sync','verify'].includes(mode)) throw Error('Usage: node scripts/gas_sync.cjs plan|auth|sync|verify');
  assertCheckout(mode==='sync');
  const revision=run('git',['rev-parse','HEAD']),bundle=sourceBundle(ROOT,revision);
  const home=path.join(ROOT,'private','gas-sync');fs.mkdirSync(home,{recursive:true,mode:0o700});
  const authFile=path.join(home,'.clasprc.json'),clasp=path.join(ROOT,'node_modules','@google','clasp','build','src','index.js');
  if(mode==='auth') {
    const login=path.join(home,'login');writeProject(login,{'appsscript.json':JSON.stringify({oauthScopes:['https://www.googleapis.com/auth/script.projects']})});
    // The human completes consent and pastes the returned URL into this local
    // terminal, never into chat. No broad default clasp scopes or CI secrets.
    run(process.execPath,[clasp,'-A',authFile,'-P',path.join(login,'.clasp.json'),'login','--use-project-scopes','--no-localhost'],{stdio:'inherit',cwd:login});return;
  }
  if(mode==='plan') {
    const stage=path.join(home,'plan');
    if(fs.existsSync(stage)) fs.rmSync(stage,{recursive:true,force:true});
    writeProject(stage,bundle.files);
    console.log(JSON.stringify({target:TARGET,sourceFingerprint:bundle.fingerprint,files:Object.keys(bundle.files),credentialConfigured:fs.existsSync(authFile),stagedUnder:'private/gas-sync/plan'},null,2));return;
  }
  if(!fs.existsSync(authFile)) throw Error('Google authorization required: run node scripts/gas_sync.cjs auth.');
  const session=path.join(home,new Date().toISOString().replace(/[:.]/g,'-'));fs.mkdirSync(session,{recursive:true,mode:0o700});
  const invoke=(dir,args)=>{if(!fs.existsSync(path.join(dir,'.clasp.json')))writeProject(dir,{});return run(process.execPath,[clasp,'-A',authFile,'-P',path.join(dir,'.clasp.json'),'-I',path.join(dir,'.claspignore'),'--json',...args],{cwd:dir});};
  const pull=dir=>{
    const roster=validatePullRoster(JSON.parse(invoke(dir,['pull'])),bundle.files);
    // Clasp lists empty sources but does not write them. Preserve them so the
    // before snapshot and the post-write comparison account for every module.
    for(const item of roster) if(!fs.existsSync(path.join(dir,item.local))) fs.writeFileSync(path.join(dir,item.local),'',{mode:0o600,flag:'wx'});
  };
  if(mode==='verify') {const after=path.join(session,'verify');pull(after);const mismatches=differences(readProject(after),bundle.files);if(mismatches.length)throw Error('Remote differs: '+mismatches.join(', '));console.log('Preview GAS matches reviewed source.');return;}
  const result=synchronize({bundle,before:path.join(session,'before'),stage:path.join(session,'stage'),after:path.join(session,'after'),pull,push:dir=>{const status=JSON.parse(invoke(dir,['show-file-status']));const roster=status.filesToPush.map(x=>path.basename(x)).sort();if(JSON.stringify(roster)!==JSON.stringify(Object.keys(bundle.files).sort()))throw Error('Clasp selected an unexpected file roster.');return invoke(dir,['push','--force']);},validate:()=>{assertCheckout(true);run(process.execPath,[path.join(ROOT,'scripts','check.cjs')],{stdio:'inherit'});assertCheckout(true);if(sourceBundle(ROOT,revision).fingerprint!==bundle.fingerprint)throw Error('Source changed during checks.');}});
  fs.writeFileSync(path.join(session,'result.json'),JSON.stringify({...result,target:TARGET,revision,fingerprint:bundle.fingerprint,sourceHashes:bundle.sourceHashes},null,2),{mode:0o600});
  console.log(JSON.stringify({...result,revision,sourceFingerprint:bundle.fingerprint}));
}
if(require.main===module) {try{main(process.argv[2]||'plan');}catch(error){console.error('GAS sync stopped: '+error.message);process.exitCode=1;}}
module.exports={TARGET,sourceBundle,assertGuard,canonical,differences,writeProject,readProject,validatePullRoster,synchronize};
